In [ ]:
import pandas as pd

In [14]:
print("Pandas ready")

Pandas ready

# Data Frame
A DataFrame is a table. It contains an array of individual entries, each of which has a certain value. Each entry corresponds to a row (or record) and a column.

In [18]:
import pandas as pd
pd.DataFrame({'yes': [50, 211], 'No': [145, 2]})

   yes   No
0   50  145
1  211    2

In [19]:
import pandas as pd
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'],
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

# Series
A Series, by contrast, is a sequence of data values. If a DataFrame is a table, a Series is a list. And in fact you can create one with nothing more than a list:

In [21]:
pd.Series([1,2,3,4,5,6])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [23]:
pd.Series([20,40,60],index =["2015 sales","2016 sales","2017 sales"],name="Product A")

2015 sales    20
2016 sales    40
2017 sales    60
Name: Product A, dtype: int64